[workspace]
resolver = "2"
members = [
    "crates/leyen-model",
    "crates/leyen-core",
    "crates/leyen-ipc",
    "crates/leyend",
    "crates/leyen",
    "crates/leyen-gtk",
]

[workspace.package]
version = "0.5.1"
authors = ["sachesi <xsachesi@pm.me>"]
edition = "2024"
license = "GPL-3.0-or-later"

[workspace.dependencies]
# Internal crates
leyen-model = { path = "crates/leyen-model" }
leyen-core = { path = "crates/leyen-core" }
leyen-ipc = { path = "crates/leyen-ipc" }

# GUI
gtk4 = { version = "0.11", features = ["v4_14"] }
libadwaita = { version = "0.9", features = ["v1_5"] }

# Serialization / config
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"

# D-Bus
zbus = { version = "5", default-features = false, features = ["tokio"] }
zvariant = "5"

# Runtime / async
tokio = { version = "1.52.1", features = ["full"] }
futures = "0.3.32"
futures-util = "0.3.32"
async-channel = "2.5.0"
crossbeam-channel = "0.5"

# Utilities
uuid = { version = "1.23.0", features = ["v4"] }
libc = "0.2"
shlex = "1.3"
directories = "6.0.0"
clap = { version = "4.6.1", features = ["derive"] }
anyhow = "1.0.102"
thiserror = "2.0.18"
log = "0.4.29"
fastrand = "2.4.1"
sha2 = "0.10.8"
hex = "0.4.3"
md-5 = "0.10"
chrono = "0.4"
gettext-rs = { version = "0.7", features = ["gettext-system"] }

# Icon extraction (GUI only)
image = { version = "0.25", default-features = false, features = ["ico", "jpeg", "png"] }
pelite = "0.10"

# Dev
tempfile = "3.27.0"
